# Generated by Django 5.0.4 on 2024-04-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_image_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
